[package]
name = "scanner"
version = "0.1.0"
authors = ["Simon Struck <simon@simonscode.org>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
crc32fast = "1.2.1"
argparse = "0.2.2"
bitflags = "1.2.1"
num-format = "0.4.0"
ansi-escapes = "0.1.0"
